### ISSUE TITLE
Guardian without violation Detection

### ISSUE THREAD

**Issue by goreil** [blockhousetech/guardian#1]
Currently, to my knowledge, it’s only possible to run Guardian with violation detection enabled. 

Since Guardian is currently the only open-source SGX-Emulator with `angr` support and already implements `SimProcedures` and `Hooks` to emulate the SGX-Environment, it would be useful to have the option to disable the violation detection. 

My current idea is to add an option disabling all the `Breakpoints` in `breakpoints.py`, since they seem to implement the violation detection. I'll try to work on that and submit a pull request if it works. 

Please tell me if you believe that there might be more problems.

**Comment by w-woloszyn** [comment]
Your PR #2  closes this :)
