### ISSUE TITLE
[BUG] Violation detection not fully disabled in simulation_procedures.py

### ISSUE THREAD

**Issue by goreil** [blockhousetech/guardian#3]
I realized that #1 is not fully closed, since some violation detection is implemented in `guardian/simulations_procedures.py`, which #2 doesn't disable. We can find these instances where `set_violation()` is called.

My plan is to write more thorough test cases (all the tests from `tests/test_violation_types.py`) and check whether each individual violation is disabled.

My pull request might take longer this time, since I need to make sure I'm not breaking the `simulation_procedures`

**Comment by w-woloszyn** [comment]
Thanks! I missed that! Do you want to add more tests before I close?

**Comment by goreil** [comment]
Since I've now tested every violation check in that were in the original Test I believe this issue closed!
